#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════
   PHAORA — Render Pipeline
   Takes a site photo + job spec, generates 4 Higgsfield img2img
   variations, scores each with Claude Vision, outputs ranked
   renders and a project README.

   Usage:
     node render.js <client-slug> [--strength 0.65] [--count 4] [--skip-check]
     phaora render <client-slug>

   Reads:  /projects/<slug>/spec.json + source.jpg
   Writes: /projects/<slug>/renders/vN-{1..4}.png
           /projects/<slug>/README.md
   ═══════════════════════════════════════════════════════════════ */

const path = require('path');
const fs = require('fs');
require('dotenv').config({ path: path.join(__dirname, '.env') });

// Also load visual-check .env for ANTHROPIC_API_KEY if not already set
if (!process.env.ANTHROPIC_API_KEY) {
  require('dotenv').config({ path: path.join(__dirname, '..', 'visual-check', '.env') });
}

const { generateVariations, pollJob, downloadResult } = require('./lib/higgsfield');
const { checkAllRenders } = require('./lib/vision-check');
const { buildPrompt } = require('./lib/prompt-builder');

/* ── CLI arg parsing ──────────────────────────────────────── */

function parseArgs(argv) {
  const args = argv.slice(2);
  const opts = { slug: null, strength: 0.65, count: 4, skipCheck: false };

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--strength' && args[i + 1]) {
      opts.strength = parseFloat(args[++i]);
    } else if (args[i] === '--count' && args[i + 1]) {
      opts.count = parseInt(args[++i], 10);
    } else if (args[i] === '--skip-check') {
      opts.skipCheck = true;
    } else if (!args[i].startsWith('-')) {
      opts.slug = args[i];
    }
  }

  return opts;
}

/* ── Version detection ────────────────────────────────────── */

function getNextVersion(rendersDir) {
  if (!fs.existsSync(rendersDir)) return 1;
  const files = fs.readdirSync(rendersDir);
  let maxVersion = 0;
  for (const f of files) {
    const match = f.match(/^v(\d+)-\d+\.png$/);
    if (match) {
      maxVersion = Math.max(maxVersion, parseInt(match[1], 10));
    }
  }
  return maxVersion + 1;
}

/* ── README generator ─────────────────────────────────────── */

function generateReadme(spec, version, results, prompt) {
  const now = new Date().toISOString().split('T')[0];
  const dims = spec.dimensions
    ? `${spec.dimensions.width_ft}ft x ${spec.dimensions.depth_ft}ft ${spec.dimensions.shape || ''}`
    : 'N/A';

  let md = `# ${spec.client_name || spec.client_slug}

**Generated:** ${now}
**Job type:** ${spec.job_type || 'patio'}
**Dimensions:** ${dims}
**Paver:** ${spec.paver?.product_name || 'N/A'} — ${spec.paver?.size_inches || '?'}" ${spec.paver?.color || ''} ${spec.paver?.pattern || ''}
**Supplier:** ${spec.paver?.supplier || 'N/A'}
**Surface:** ${spec.surface_area || 'N/A'}

## Prompt

\`\`\`
${prompt}
\`\`\`

## Renders (v${version})

`;

  if (results && results.length > 0) {
    md += `| Render | Score | Photoreal | Pattern | Usable | Notes |\n`;
    md += `|--------|-------|-----------|---------|--------|-------|\n`;
    for (const r of results) {
      const fname = path.basename(r.path);
      md += `| ${fname} | ${r.score} | ${r.photoreal} | ${r.pattern_correct ? 'yes' : 'no'} | ${r.usable ? 'yes' : 'no'} | ${r.notes || ''} |\n`;
    }
  } else {
    md += `Vision check was skipped. Renders saved to \`renders/\` folder.\n`;
  }

  md += `\n---\n*Generated by PHAORA render pipeline*\n`;
  return md;
}

/* ── Main pipeline ────────────────────────────────────────── */

async function main() {
  const opts = parseArgs(process.argv);

  if (!opts.slug) {
    console.error('Usage: node render.js <client-slug> [--strength 0.65] [--count 4] [--skip-check]');
    process.exit(1);
  }

  const REPO_ROOT = path.resolve(__dirname, '..', '..');
  const projectDir = path.join(REPO_ROOT, 'projects', opts.slug);
  const specPath = path.join(projectDir, 'spec.json');
  const rendersDir = path.join(projectDir, 'renders');

  /* ── Step 1: Validate inputs ─────────────────────────── */

  console.log(`\nPHAORA Render Pipeline`);
  console.log(`${'='.repeat(50)}`);
  console.log(`Project: ${opts.slug}`);
  console.log(`Directory: ${projectDir}\n`);

  if (!fs.existsSync(projectDir)) {
    console.error(`Project directory not found: ${projectDir}`);
    console.error(`Create it with spec.json and source.jpg first.`);
    process.exit(1);
  }

  if (!fs.existsSync(specPath)) {
    console.error(`spec.json not found at: ${specPath}`);
    process.exit(1);
  }

  let spec;
  try {
    spec = JSON.parse(fs.readFileSync(specPath, 'utf8'));
  } catch (err) {
    console.error(`Invalid spec.json: ${err.message}`);
    process.exit(1);
  }

  // Resolve source photo path (relative to project dir or absolute)
  const sourcePhotoRel = spec.source_photo || './source.jpg';
  const sourcePath = path.resolve(projectDir, sourcePhotoRel);
  if (!fs.existsSync(sourcePath)) {
    console.error(`Source photo not found: ${sourcePath}`);
    console.error(`Place the site photo as source.jpg in the project folder.`);
    process.exit(1);
  }

  console.log(`Spec loaded: ${spec.client_name || opts.slug}`);
  console.log(`Source photo: ${sourcePath}`);
  console.log(`Job type: ${spec.job_type || 'patio'}`);
  if (spec.paver) {
    console.log(`Paver: ${spec.paver.product_name || 'N/A'} (${spec.paver.size_inches}" ${spec.paver.color} ${spec.paver.pattern})`);
  }

  /* ── Step 2: Build prompt ────────────────────────────── */

  const prompt = buildPrompt(spec);

  console.log(`\nPrompt:\n  ${prompt}\n`);

  /* ── Step 3: Determine version ───────────────────────── */

  if (!fs.existsSync(rendersDir)) fs.mkdirSync(rendersDir, { recursive: true });
  const version = getNextVersion(rendersDir);
  console.log(`Render version: v${version}`);
  console.log(`Generating ${opts.count} variations (strength: ${opts.strength})...\n`);

  /* ── Step 4: Submit jobs to Higgsfield ───────────────── */

  const imageBuffer = fs.readFileSync(sourcePath);

  let jobs;
  try {
    console.log('Uploading source image to Higgsfield...');
    jobs = await generateVariations(imageBuffer, prompt, opts.count);
  } catch (err) {
    console.error(`Higgsfield submission failed: ${err.message}`);
    process.exit(1);
  }

  console.log(`Submitted ${jobs.length} jobs. Polling for results...\n`);

  /* ── Step 5: Poll and download results ───────────────── */

  const renderPaths = [];

  for (const job of jobs) {
    const idx = job.index + 1;
    const outPath = path.join(rendersDir, `v${version}-${idx}.png`);
    const label = `v${version}-${idx}`;

    try {
      process.stdout.write(`  [${label}] Waiting...`);
      const result = await pollJob(job.requestId, {
        onPoll: (status, elapsed) => {
          const secs = Math.round(elapsed / 1000);
          process.stdout.write(`\r  [${label}] ${status} (${secs}s)   `);
        },
      });
      process.stdout.write(`\r  [${label}] Completed. Downloading...      \n`);

      await downloadResult(result.imageUrl, outPath);
      console.log(`  [${label}] Saved -> renders/${label}.png`);
      renderPaths.push({ path: outPath, label });
    } catch (err) {
      console.error(`\n  [${label}] FAILED: ${err.message}`);
      renderPaths.push({ path: outPath, label, failed: true });
    }
  }

  const successfulRenders = renderPaths.filter(r => !r.failed);
  console.log(`\n${successfulRenders.length}/${opts.count} renders downloaded.\n`);

  if (successfulRenders.length === 0) {
    console.error('No renders succeeded. Check Higgsfield credentials and API status.');
    process.exit(1);
  }

  /* ── Step 6: Vision check ────────────────────────────── */

  let results = null;

  if (!opts.skipCheck) {
    if (!process.env.ANTHROPIC_API_KEY) {
      console.log('ANTHROPIC_API_KEY not set — skipping vision check.');
      console.log('Add it to .env to enable Claude Vision scoring.\n');
    } else {
      console.log('Running Claude Vision check on renders...\n');

      const renderInputs = successfulRenders.map(r => ({
        path: r.path,
        label: r.label,
        buffer: fs.readFileSync(r.path),
      }));

      try {
        results = await checkAllRenders(renderInputs);

        console.log('  Score  Photoreal  Pattern  Usable  Render');
        console.log('  ─────  ─────────  ───────  ──────  ──────');
        for (const r of results) {
          const pat = r.pattern_correct ? 'yes' : 'NO';
          const use = r.usable ? 'yes' : 'NO';
          const score = String(r.score).padStart(3);
          console.log(`  ${score}    ${r.photoreal.padEnd(9)}  ${pat.padEnd(7)}  ${use.padEnd(6)}  ${r.label}`);
        }
        console.log(`\n  Notes:`);
        for (const r of results) {
          console.log(`  ${r.label}: ${r.notes}`);
        }
        console.log('');
      } catch (err) {
        console.error(`Vision check error: ${err.message}`);
        console.log('Renders saved but scores unavailable.\n');
      }
    }
  } else {
    console.log('Vision check skipped (--skip-check).\n');
  }

  /* ── Step 7: Write README ────────────────────────────── */

  const readmePath = path.join(projectDir, 'README.md');
  const readme = generateReadme(spec, version, results, prompt);
  fs.writeFileSync(readmePath, readme);
  console.log(`README written -> projects/${opts.slug}/README.md`);

  /* ── Done ────────────────────────────────────────────── */

  console.log(`\nDone. Renders saved to projects/${opts.slug}/renders/`);
  if (results) {
    const best = results[0];
    console.log(`Best render: ${best.label} (score: ${best.score})`);
  }

  // Copy source photo if not already in project dir
  const expectedSource = path.join(projectDir, 'source.jpg');
  if (sourcePath !== expectedSource && !fs.existsSync(expectedSource)) {
    fs.copyFileSync(sourcePath, expectedSource);
  }

  process.exit(0);
}

main().catch(err => {
  console.error(`\nFatal error: ${err.message}`);
  if (process.env.DEBUG) console.error(err.stack);
  process.exit(1);
});
